**Numpy Array**

In [1]:
import numpy as np

In [2]:
myarray=np.array([3,6,3244444,7],np.int64) #giving data type int 8 bcz now you can mange your memory


In [3]:
myarray.dtype
myarray[2]=233 #updating the value

In [4]:
myarray[2]
# myarray[0]
# myarray.shape

233

In [5]:
twoD_array=np.array([[3,6,32,7],[23,4,2,52]])

In [6]:
twoD_array[1,2]
twoD_array.dtype
# print(twoD_array)
# twoD_array.shape

dtype('int32')

**Numpy Array creation method:**

**1. Python data structures to numpy array:**

Existing Python data structures to numpy array conversion(list,tuples into numpy array as above we done)

In [7]:
listarray=np.array([[1,2,3],[4,5,6],[7,8,9]]) #2D array

In [8]:
print(listarray)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [9]:
listarray.shape

(3, 3)

In [10]:
listarray.size

9

In [11]:
listarray.dtype

dtype('int32')

In [12]:
setarray=np.array({1,43,52})

In [13]:
setarray

array({1, 43, 52}, dtype=object)

we can use other python structures to make our numpy array like dictionary etc

**2.Intrinsic Numpy array creation:**

In [14]:
zerosarr=np.zeros(2) #1D

In [15]:
zerosarr

array([0., 0.])

In [16]:
zerosarr.shape

(2,)

In [17]:
zeros2d=np.zeros((2,5))

In [18]:

zeros2d  #2by5 array

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [19]:
zeros2d.shape

(2, 5)

In [20]:
rng=np.arange(10) #it gives till given range

In [21]:
rng

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [22]:
lspace=np.linspace(1,20,4)  #it gives equally linear spaces elements till given range

In [23]:
lspace

array([ 1.        ,  7.33333333, 13.66666667, 20.        ])

In [24]:
emp=np.empty((2,5)) #it gives empty array of given size and dimention 

In [25]:
emp

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [26]:
emp_like=np.empty_like(lspace) #in this we give the previous array it makes same array as previous

In [27]:
emp_like

array([ 1.        ,  7.33333333, 13.66666667, 20.        ])

In [28]:
ident=np.identity(4) # it gives identity matrix of size

In [29]:
ident

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [30]:
arr=np.arange(99)

In [31]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98])

In [32]:
# arr.reshape(3,34) size is 99 so we cannot do it it should equal sized
arr=arr.reshape(3,33) #it converts into 2D

In [33]:
arr.shape


(3, 33)

In [34]:
arr

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31,
        32],
       [33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48,
        49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64,
        65],
       [66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81,
        82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97,
        98]])

In [35]:
arr=arr.ravel() #it converts it into 1D 

In [36]:
arr.shape

(99,)

**Numpy Axis**

In 1D there is only Axis 0 (there only rows action in 1 row matrix)

In 2D there are Axis 0 (Rows representation) & Axis 1(Columns representation)

In [37]:
x=[[1,2,3],[4,5,6],[7,1,0]]

In [38]:
ar=np.array(x)

In [39]:
ar

array([[1, 2, 3],
       [4, 5, 6],
       [7, 1, 0]])

In [40]:
ar.sum(axis=0) #all rows sum

array([12,  8,  9])

In [41]:
ar.sum(axis=1) #all columns sum

array([ 6, 15,  8])

**Numpy Methods and Attributes:**

method are with() and attributes are simple


In [42]:
ar.flat #it gives iterator

In [43]:
for item in ar.flat: #we can print all item of matrix in itereator 
    print(item)

1
2
3
4
5
6
7
1
0


In [44]:
ar.T  #it used to take transpose of the matrix or array

array([[1, 4, 7],
       [2, 5, 1],
       [3, 6, 0]])

In [45]:
ar.ndim #it tells the dimention of our array/matrix

2

In [46]:
ar.size #it tells total elements in the array

9

In [47]:
ar.nbytes #total consumed bytes

36

In [48]:
oneD=np.array([4,2,53,5])

In [49]:
oneD.argmax() #gives index of max element

2

In [50]:
oneD.argmin()

1

In [51]:
oneD.argsort() #indexes in sorted order

array([1, 0, 3, 2], dtype=int64)

In [52]:
ar

array([[1, 2, 3],
       [4, 5, 6],
       [7, 1, 0]])

In [53]:
ar.argmax() #it counts it from 0 to first rows column then next rows column

6

In [54]:
ar.argmin()

8

In [55]:
ar.argmax(axis=0)

array([2, 1, 1], dtype=int64)

In [56]:
ar.argmax(axis=1)

array([2, 2, 0], dtype=int64)

In [57]:
ar.argmin(axis=0)


array([0, 2, 2], dtype=int64)

In [58]:
ar.argsort() #indexes in sorted order

array([[0, 1, 2],
       [0, 1, 2],
       [2, 1, 0]], dtype=int64)

In [59]:
ar.ravel()

array([1, 2, 3, 4, 5, 6, 7, 1, 0])

In [60]:
ar.reshape((9,1)) #it means we can reshape in the multiples of total size

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6],
       [7],
       [1],
       [0]])

**Math operations on the Numpy Array**

In [61]:
ar

array([[1, 2, 3],
       [4, 5, 6],
       [7, 1, 0]])

In [62]:
ar2=np.array([[1, 2, 1],[4, 0, 6],[8, 1, 0]])

In [63]:
ar2+ar #matrix addition

array([[ 2,  4,  4],
       [ 8,  5, 12],
       [15,  2,  0]])

In [64]:
[2,5,64]+[46,62,8] #in list we cannot do addition it extends the list but in array we can do

[2, 5, 64, 46, 62, 8]

In [65]:
ar

array([[1, 2, 3],
       [4, 5, 6],
       [7, 1, 0]])

In [66]:
ar2

array([[1, 2, 1],
       [4, 0, 6],
       [8, 1, 0]])

In [67]:
ar*ar2 #elementvise multiplication

array([[ 1,  4,  3],
       [16,  0, 36],
       [56,  1,  0]])

In [68]:
np.sqrt(ar2)

array([[1.        , 1.41421356, 1.        ],
       [2.        , 0.        , 2.44948974],
       [2.82842712, 1.        , 0.        ]])

In [69]:
ar2.max()

8

In [70]:
ar2.min()

0

In [71]:
ar2.sum()

23

In [72]:
ar

array([[1, 2, 3],
       [4, 5, 6],
       [7, 1, 0]])

In [73]:
np.where(ar>5)

(array([1, 2], dtype=int64), array([2, 0], dtype=int64))

In [74]:
np.count_nonzero(ar)

8

In [75]:
np.count_nonzero(ar2)

7

In [76]:
ar2

array([[1, 2, 1],
       [4, 0, 6],
       [8, 1, 0]])

In [77]:
np.nonzero(ar2)

(array([0, 0, 0, 1, 1, 2, 2], dtype=int64),
 array([0, 1, 2, 0, 2, 0, 1], dtype=int64))

In [78]:
ar[0,0]=0

In [79]:
np.nonzero(ar)

(array([0, 0, 1, 1, 1, 2, 2], dtype=int64),
 array([1, 2, 0, 1, 2, 0, 1], dtype=int64))

In [81]:
ar.tolist() #it convert array to list

[[0, 2, 3], [4, 5, 6], [7, 1, 0]]

array concatination

In [82]:
x = np.array([1, 2, 3])
y = np.array([3, 2, 1])
z = [21,21,21]

In [84]:
np.concatenate([x,y,z])

array([ 1,  2,  3,  3,  2,  1, 21, 21, 21])

In [85]:
n1=np.random.randint(15,size=(2,7))
print(n1)

[[14  7  5  5  9 11  9]
 [13  3 14  6  2  7  9]]


In [86]:
n2=np.random.randint(15,size=(2,7))
print(n2)

[[ 2  4 13  7  0  2  6]
 [ 4  7  3  7  6 13 14]]


In [87]:
np.concatenate([n1,n2])

array([[14,  7,  5,  5,  9, 11,  9],
       [13,  3, 14,  6,  2,  7,  9],
       [ 2,  4, 13,  7,  0,  2,  6],
       [ 4,  7,  3,  7,  6, 13, 14]])

In [89]:
a=np.array([[1,2],[3,4]])
b=np.array([[4,5],[6,7]])
print(a)
print(b)

[[1 2]
 [3 4]]
[[4 5]
 [6 7]]


In [93]:

np.sum([a,b])

32

In [94]:
np.sum([a,b],axis=1) #add horizantally

array([[ 4,  6],
       [10, 12]])

In [96]:
np.sum([a,b],axis=0) #add vertically

array([[ 5,  7],
       [ 9, 11]])

In [98]:
a=np.array([[1, 2],[3, 4]])
b=np.array([[4, 5],[6, 7]])
print(a)
print(b)

[[1 2]
 [3 4]]
[[4 5]
 [6 7]]


In [100]:
np.vstack([a,b]) #joining vertically array upon array

array([[1, 2],
       [3, 4],
       [4, 5],
       [6, 7]])

In [101]:
np.hstack([a,b]) #joining horizantally, array with array

array([[1, 2, 4, 5],
       [3, 4, 6, 7]])

In [103]:
np.column_stack([a,b]) 

array([[1, 2, 4, 5],
       [3, 4, 6, 7]])